
server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=usuario-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/usuarios/**

spring.cloud.gateway.routes[1].id=conductor-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/conductores/**

spring.cloud.gateway.routes[2].id=viaje-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/viajes/**

spring.cloud.gateway.routes[3].id=vehiculo-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/vehiculos/**

spring.cloud.gateway.routes[4].id=ms-auth
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.routes[5].id=pago-service
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/pagos/**

